export { SignIn } from "../auth";
export { SignUp } from "../auth";
export { SignOut } from "../auth";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Profile } from "./Profile";
export { DiaryPage } from "./Diary";
export { DialogsPage } from "./Dialogs";
export { StatisticsPage } from "./Statistics";
export { ThematicMaterialsPage } from "./ThematicMaterials";
export { ThematicMaterialPage } from "./ThematicMaterial";
export { RelativePage } from "./Relative";
export { DoctorPage } from "./Doctor";
export { ReviewsPage } from "./Reviews";
export { HealthStatesPage } from "./HealthStates";
export { NotificationsPage } from "./Notifications";
